version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/services/governance-api"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
      timezone: "UTC"
    open-pull-requests-limit: 5

  - package-ecosystem: "terraform"
    directory: "/infra"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:15"
      timezone: "UTC"
    open-pull-requests-limit: 5

  - package-ecosystem: "docker"
    directories:
      - "/services/governance-api"
      - "/services/mock-telemetry"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:30"
      timezone: "UTC"
    open-pull-requests-limit: 3

  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:45"
      timezone: "UTC"
    open-pull-requests-limit: 2